### ISSUE TITLE
Rotation is not applied correctly with parent-child relation

### ISSUE THREAD

**Issue by emilekberg** [emilekberg/onodrim#2]
Rotating a object that has a child with an offset, should offset the position of said child as well. 
As of now, the child simply apply just the parents rotation, but the position is static.

**Comment by Froggi** [comment]
Checkout commit in branch transform2d-matrix. 

Only i dont like the following:
```
let newMat = new Matrix3();
newMat.copy(this._localMatrix);
newMat.multiply(this._globalMatrix);
this._globalMatrix.copy(newMat);
```

But the following doesnt multiply in correct order:
`this._globalMatrix.multiply(this._localMatrix);`

Maybe im just tired and cant see a better way of writing it.

**Comment by Froggi** [comment]
New version commited, looking for feedback.

**Comment by emilekberg** [comment]
Much better :) just a minor note added. good job!
